name: my test

on:
  push:
    branches: [ main ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: check out code
      uses: actions/checkout@v2
      
    - name: Setting variable
      env:
        MY_NAME: Alva
      run: | 
        echo Hello, $MY_NAME
        echo Your name is $MY_NAME
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 
    
    - name: execute py script
      run: | 
        python steve.py
